version: "3.7"

services:
  db:
    image: mysql:latest
    container_name: avatar-app
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: avatar
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
      MYSQL_USER: user
    volumes:
      - ./docker-compose/mysql:/var/lib
      - ./application/api/migration:/migration
    networks:
      - database

  redis:
    image: redis:4.0
    container_name: app_redis
    ports:
      - "6382:6379"
    networks:
      - database

  nginx:
    image: nginx:1.20.0
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - database

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker-compose/rabbit:/var/lib/rabbitmq/
      - ./log/:/var/log/rabbitmq
    networks:
      - database


  app:
    build:
      args:
        user: avatar
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: nginx-app
    restart: unless-stopped
    environment:
      REDIS_HOST: app_redis
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - database

networks:
  database:
    driver: bridge