version: '3.5'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
      MYSQL_USER: admin
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib
    networks:
      - database

networks:
  database:
