version: "3.7"

services:
  db:
    image: mariadb:latest
    container_name: avatar-app
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: avatar
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
      MYSQL_USER: user
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - database

  nginx:
    image: nginx:1.20.0
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - database

  app:
    build:
      args:
        user: avatar
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: nginx-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - database

networks:
  database:
    driver: bridge